/**
 * This file was generated by the Jeddict
 */
package com.udea.concesionariolab.com.udea.concesionariolab.entity;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * @author David
 */
@Entity(name = "TipoVehiculo")
public class TipoVehiculo {

    @Column(name = "id", unique = true, nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(name = "tipo_vehiculo", nullable = false)
    @Basic
    private String tipo_vehiculo;

    @OneToMany(mappedBy = "tipoVehiculo")
    private List<Vehiculo> vehiculoes;

    public TipoVehiculo(Long id, String tipo_vehiculo, List<Vehiculo> vehiculoes) {
        this.id = id;
        this.tipo_vehiculo = tipo_vehiculo;
        this.vehiculoes = vehiculoes;
    }

    public TipoVehiculo() {
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTipo_vehiculo() {
        return this.tipo_vehiculo;
    }

    public void setTipo_vehiculo(String tipo_vehiculo) {
        this.tipo_vehiculo = tipo_vehiculo;
    }

    public List<Vehiculo> getVehiculoes() {
        if (vehiculoes == null) {
            vehiculoes = new ArrayList<>();
        }
        return this.vehiculoes;
    }

    public void setVehiculoes(List<Vehiculo> vehiculoes) {
        this.vehiculoes = vehiculoes;
    }

    public void addVehiculo(Vehiculo vehiculo) {
        getVehiculoes().add(vehiculo);
        vehiculo.setTipoVehiculo(this);
    }

    public void removeVehiculo(Vehiculo vehiculo) {
        getVehiculoes().remove(vehiculo);
        vehiculo.setTipoVehiculo(null);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final TipoVehiculo other = (TipoVehiculo) obj;
        if (!java.util.Objects.equals(this.getId(), other.getId())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + Objects.hashCode(this.getId());
        return hash;
    }

    @Override
    public String toString() {
        return "TipoVehiculo{" + " id=" + id + ", tipo_vehiculo=" + tipo_vehiculo + ", vehiculoes=" + vehiculoes + '}';
    }

}