//
// This file was generated by the Jeddict
//
package com.udea.concesionariolab.com.udea.concesionariolab.entity;

import java.io.Serializable;
import java.util.Objects;

public class VehiculoPK implements Serializable {

    private Long id;

    private Long tipoVehiculo;

    public VehiculoPK() {
    }

    public VehiculoPK(Long id, Long tipoVehiculo) {
        this.id = id;
        this.tipoVehiculo = tipoVehiculo;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTipoVehiculo() {
        return this.tipoVehiculo;
    }

    public void setTipoVehiculo(Long tipoVehiculo) {
        this.tipoVehiculo = tipoVehiculo;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final VehiculoPK other = (VehiculoPK) obj;
        if (!java.util.Objects.equals(this.getId(), other.getId())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getTipoVehiculo(), other.getTipoVehiculo())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + Objects.hashCode(this.getId());
        hash = 31 * hash + Objects.hashCode(this.getTipoVehiculo());
        return hash;
    }

    @Override
    public String toString() {
        return "VehiculoPK{" + " id=" + id + ", tipoVehiculo=" + tipoVehiculo + '}';
    }

}