    /**
     * This file was generated by the Jeddict
     */
    package com.udea.concesionariolab.com.udea.concesionariolab.entity;

    import java.util.Date;
    import java.util.Objects;
    import javax.persistence.Basic;
    import javax.persistence.Column;
    import javax.persistence.Entity;
    import javax.persistence.GeneratedValue;
    import javax.persistence.GenerationType;
    import javax.persistence.Id;
    import javax.persistence.IdClass;
    import javax.persistence.Lob;
    import javax.persistence.ManyToOne;
    import javax.persistence.Temporal;
    import javax.persistence.TemporalType;
    import javax.validation.constraints.PastOrPresent;
    import javax.validation.constraints.PositiveOrZero;

    /**
     * @author David
     */
    
    // Tuvimos muchisimos problemas con el código y la conexión de la BD en esta clase al momento de guardar
    @Entity(name = "Vehiculo")
    @IdClass(VehiculoPK.class)
    public class Vehiculo {

        @Column(name = "id", unique = true, nullable = false)
        @Id
        @GeneratedValue(strategy = GenerationType.AUTO)
        private Long id;

        @Column(name = "nombre", nullable = false)
        @Basic
        private String nombre;

        @Column(name = "modelo", nullable = false)
        @Basic
        private String modelo;

        @Column(name = "marca", nullable = false)
        @Basic
        private String marca;

        @Column(name = "foto", nullable = false)
        @Lob
        @Basic
        private byte[] foto;

        @Column(name = "fecha_ingreso", nullable = false)
        @Basic
        @Temporal(TemporalType.DATE)
        private Date fecha_ingreso;

        @Column(name = "precio", nullable = false)
        @Basic
        private double precio;

        @Column(name = "cantidad_disponible", nullable = false)
        @Basic
        private int cantidad_disponible;

        @Id
        @ManyToOne
        private TipoVehiculo tipoVehiculo;

        public Vehiculo(Long id, String nombre, String modelo, String marca, byte[] foto, Date fecha_ingreso, double precio, int cantidad_disponible, TipoVehiculo tipoVehiculo) {
            this.id = id;
            this.nombre = nombre;
            this.modelo = modelo;
            this.marca = marca;
            this.foto = foto;
            this.fecha_ingreso = fecha_ingreso;
            this.precio = precio;
            this.cantidad_disponible = cantidad_disponible;
            this.tipoVehiculo = tipoVehiculo;
        }

        public Vehiculo() {
        }

        public Long getId() {
            return this.id;
        }

        public void setId(Long id) {
            this.id = id;
        }

        public String getNombre() {
            return this.nombre;
        }

        public void setNombre(String nombre) {
            this.nombre = nombre;
        }

        public String getModelo() {
            return this.modelo;
        }

        public void setModelo(String modelo) {
            this.modelo = modelo;
        }

        public String getMarca() {
            return this.marca;
        }

        public void setMarca(String marca) {
            this.marca = marca;
        }

        public byte[] getFoto() {
            return this.foto;
        }

        public void setFoto(byte[] foto) {
            this.foto = foto;
        }

        public Date getFecha_ingreso() {
            return this.fecha_ingreso;
        }

        public void setFecha_ingreso(Date fecha_ingreso) {
            this.fecha_ingreso = fecha_ingreso;
        }

        public double getPrecio() {
            return this.precio;
        }

        public void setPrecio(double precio) {
            this.precio = precio;
        }

        public int getCantidad_disponible() {
            return this.cantidad_disponible;
        }

        public void setCantidad_disponible(int cantidad_disponible) {
            this.cantidad_disponible = cantidad_disponible;
        }

        public TipoVehiculo getTipoVehiculo() {
            return this.tipoVehiculo;
        }

        public void setTipoVehiculo(TipoVehiculo tipoVehiculo) {
            this.tipoVehiculo = tipoVehiculo;
        }

        @Override
        public boolean equals(Object obj) {
            if (obj == null) {
                return false;
            }
            if (!Objects.equals(getClass(), obj.getClass())) {
                return false;
            }
            final Vehiculo other = (Vehiculo) obj;
            if (!java.util.Objects.equals(this.getId(), other.getId())) {
                return false;
            }
            return true;
        }

        @Override
        public int hashCode() {
            int hash = 7;
            hash = 31 * hash + Objects.hashCode(this.getId());
            return hash;
        }

        @Override
        public String toString() {
            return "Vehiculo{" + " id=" + id + ", nombre=" + nombre + ", modelo=" + modelo + ", marca=" + marca + ", foto=" + foto + ", fecha_ingreso=" + fecha_ingreso + ", precio=" + precio + ", cantidad_disponible=" + cantidad_disponible + ", tipoVehiculo=" + tipoVehiculo + '}';
        }

    }